[project]
name = "semantic-kernel-test"
version = "0.1.0"
description = "A console app testing semantic-kernel"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "semantic-kernel[ollama]>=1.28.0",
]
